//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp.Reference_NowPlatform {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.service-now.com/x_264731_choreszer_customers", ConfigurationName="Reference_NowPlatform.ServiceNowSoap")]
    public interface ServiceNowSoap {
        
        // CODEGEN: Generating message contract since the operation insert is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/x_264731_choreszer_customers/insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Temp.Reference_NowPlatform.insertResponse1 insert(Temp.Reference_NowPlatform.insertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/x_264731_choreszer_customers/insert", ReplyAction="*")]
        System.Threading.Tasks.Task<Temp.Reference_NowPlatform.insertResponse1> insertAsync(Temp.Reference_NowPlatform.insertRequest request);
        
        // CODEGEN: Generating message contract since the operation update is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/x_264731_choreszer_customers/update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Temp.Reference_NowPlatform.updateResponse1 update(Temp.Reference_NowPlatform.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/x_264731_choreszer_customers/update", ReplyAction="*")]
        System.Threading.Tasks.Task<Temp.Reference_NowPlatform.updateResponse1> updateAsync(Temp.Reference_NowPlatform.updateRequest request);
        
        // CODEGEN: Generating message contract since the operation deleteMultiple is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/x_264731_choreszer_customers/deleteMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Temp.Reference_NowPlatform.deleteMultipleResponse1 deleteMultiple(Temp.Reference_NowPlatform.deleteMultipleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/x_264731_choreszer_customers/deleteMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<Temp.Reference_NowPlatform.deleteMultipleResponse1> deleteMultipleAsync(Temp.Reference_NowPlatform.deleteMultipleRequest request);
        
        // CODEGEN: Generating message contract since the operation getKeys is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/x_264731_choreszer_customers/getKeys", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Temp.Reference_NowPlatform.getKeysResponse1 getKeys(Temp.Reference_NowPlatform.getKeysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/x_264731_choreszer_customers/getKeys", ReplyAction="*")]
        System.Threading.Tasks.Task<Temp.Reference_NowPlatform.getKeysResponse1> getKeysAsync(Temp.Reference_NowPlatform.getKeysRequest request);
        
        // CODEGEN: Generating message contract since the operation deleteRecord is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/x_264731_choreszer_customers/deleteRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Temp.Reference_NowPlatform.deleteRecordResponse1 deleteRecord(Temp.Reference_NowPlatform.deleteRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/x_264731_choreszer_customers/deleteRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<Temp.Reference_NowPlatform.deleteRecordResponse1> deleteRecordAsync(Temp.Reference_NowPlatform.deleteRecordRequest request);
        
        // CODEGEN: Generating message contract since the operation get is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/x_264731_choreszer_customers/get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Temp.Reference_NowPlatform.getResponse1 get(Temp.Reference_NowPlatform.getRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/x_264731_choreszer_customers/get", ReplyAction="*")]
        System.Threading.Tasks.Task<Temp.Reference_NowPlatform.getResponse1> getAsync(Temp.Reference_NowPlatform.getRequest request);
        
        // CODEGEN: Generating message contract since the operation getRecords is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/x_264731_choreszer_customers/getRecords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Temp.Reference_NowPlatform.getRecordsResponse getRecords(Temp.Reference_NowPlatform.getRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.service-now.com/x_264731_choreszer_customers/getRecords", ReplyAction="*")]
        System.Threading.Tasks.Task<Temp.Reference_NowPlatform.getRecordsResponse> getRecordsAsync(Temp.Reference_NowPlatform.getRecordsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/x_264731_choreszer_customers")]
    public partial class insert : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string first_nameField;
        
        private string last_nameField;
        
        private string numberField;
        
        private string phone_numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                this.first_nameField = value;
                this.RaisePropertyChanged("first_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
                this.RaisePropertyChanged("last_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string phone_number {
            get {
                return this.phone_numberField;
            }
            set {
                this.phone_numberField = value;
                this.RaisePropertyChanged("phone_number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/x_264731_choreszer_customers")]
    public partial class insertResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sys_idField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/x_264731_choreszer_customers", Order=0)]
        public Temp.Reference_NowPlatform.insert insert;
        
        public insertRequest() {
        }
        
        public insertRequest(Temp.Reference_NowPlatform.insert insert) {
            this.insert = insert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/x_264731_choreszer_customers", Order=0)]
        public Temp.Reference_NowPlatform.insertResponse insertResponse;
        
        public insertResponse1() {
        }
        
        public insertResponse1(Temp.Reference_NowPlatform.insertResponse insertResponse) {
            this.insertResponse = insertResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/x_264731_choreszer_customers")]
    public partial class update : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string first_nameField;
        
        private string last_nameField;
        
        private string numberField;
        
        private string phone_numberField;
        
        private string sys_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                this.first_nameField = value;
                this.RaisePropertyChanged("first_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
                this.RaisePropertyChanged("last_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string phone_number {
            get {
                return this.phone_numberField;
            }
            set {
                this.phone_numberField = value;
                this.RaisePropertyChanged("phone_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/x_264731_choreszer_customers")]
    public partial class updateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sys_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/x_264731_choreszer_customers", Order=0)]
        public Temp.Reference_NowPlatform.update update;
        
        public updateRequest() {
        }
        
        public updateRequest(Temp.Reference_NowPlatform.update update) {
            this.update = update;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/x_264731_choreszer_customers", Order=0)]
        public Temp.Reference_NowPlatform.updateResponse updateResponse;
        
        public updateResponse1() {
        }
        
        public updateResponse1(Temp.Reference_NowPlatform.updateResponse updateResponse) {
            this.updateResponse = updateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/x_264731_choreszer_customers")]
    public partial class deleteMultiple : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string first_nameField;
        
        private string last_nameField;
        
        private string numberField;
        
        private string phone_numberField;
        
        private string sys_created_byField;
        
        private string sys_created_onField;
        
        private string sys_idField;
        
        private string sys_mod_countField;
        
        private string sys_updated_byField;
        
        private string sys_updated_onField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                this.first_nameField = value;
                this.RaisePropertyChanged("first_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
                this.RaisePropertyChanged("last_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string phone_number {
            get {
                return this.phone_numberField;
            }
            set {
                this.phone_numberField = value;
                this.RaisePropertyChanged("phone_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sys_created_by {
            get {
                return this.sys_created_byField;
            }
            set {
                this.sys_created_byField = value;
                this.RaisePropertyChanged("sys_created_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sys_created_on {
            get {
                return this.sys_created_onField;
            }
            set {
                this.sys_created_onField = value;
                this.RaisePropertyChanged("sys_created_on");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=7)]
        public string sys_mod_count {
            get {
                return this.sys_mod_countField;
            }
            set {
                this.sys_mod_countField = value;
                this.RaisePropertyChanged("sys_mod_count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string sys_updated_by {
            get {
                return this.sys_updated_byField;
            }
            set {
                this.sys_updated_byField = value;
                this.RaisePropertyChanged("sys_updated_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string sys_updated_on {
            get {
                return this.sys_updated_onField;
            }
            set {
                this.sys_updated_onField = value;
                this.RaisePropertyChanged("sys_updated_on");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/x_264731_choreszer_customers")]
    public partial class deleteMultipleResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteMultipleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/x_264731_choreszer_customers", Order=0)]
        public Temp.Reference_NowPlatform.deleteMultiple deleteMultiple;
        
        public deleteMultipleRequest() {
        }
        
        public deleteMultipleRequest(Temp.Reference_NowPlatform.deleteMultiple deleteMultiple) {
            this.deleteMultiple = deleteMultiple;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteMultipleResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/x_264731_choreszer_customers", Order=0)]
        public Temp.Reference_NowPlatform.deleteMultipleResponse deleteMultipleResponse;
        
        public deleteMultipleResponse1() {
        }
        
        public deleteMultipleResponse1(Temp.Reference_NowPlatform.deleteMultipleResponse deleteMultipleResponse) {
            this.deleteMultipleResponse = deleteMultipleResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/x_264731_choreszer_customers")]
    public partial class getKeys : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string first_nameField;
        
        private string last_nameField;
        
        private string numberField;
        
        private string phone_numberField;
        
        private string sys_created_byField;
        
        private string sys_created_onField;
        
        private string sys_mod_countField;
        
        private string sys_updated_byField;
        
        private string sys_updated_onField;
        
        private string @__use_viewField;
        
        private string @__encoded_queryField;
        
        private string @__limitField;
        
        private string @__first_rowField;
        
        private string @__last_rowField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                this.first_nameField = value;
                this.RaisePropertyChanged("first_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
                this.RaisePropertyChanged("last_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string phone_number {
            get {
                return this.phone_numberField;
            }
            set {
                this.phone_numberField = value;
                this.RaisePropertyChanged("phone_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sys_created_by {
            get {
                return this.sys_created_byField;
            }
            set {
                this.sys_created_byField = value;
                this.RaisePropertyChanged("sys_created_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sys_created_on {
            get {
                return this.sys_created_onField;
            }
            set {
                this.sys_created_onField = value;
                this.RaisePropertyChanged("sys_created_on");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=6)]
        public string sys_mod_count {
            get {
                return this.sys_mod_countField;
            }
            set {
                this.sys_mod_countField = value;
                this.RaisePropertyChanged("sys_mod_count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string sys_updated_by {
            get {
                return this.sys_updated_byField;
            }
            set {
                this.sys_updated_byField = value;
                this.RaisePropertyChanged("sys_updated_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string sys_updated_on {
            get {
                return this.sys_updated_onField;
            }
            set {
                this.sys_updated_onField = value;
                this.RaisePropertyChanged("sys_updated_on");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string @__use_view {
            get {
                return this.@__use_viewField;
            }
            set {
                this.@__use_viewField = value;
                this.RaisePropertyChanged("__use_view");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string @__encoded_query {
            get {
                return this.@__encoded_queryField;
            }
            set {
                this.@__encoded_queryField = value;
                this.RaisePropertyChanged("__encoded_query");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string @__limit {
            get {
                return this.@__limitField;
            }
            set {
                this.@__limitField = value;
                this.RaisePropertyChanged("__limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string @__first_row {
            get {
                return this.@__first_rowField;
            }
            set {
                this.@__first_rowField = value;
                this.RaisePropertyChanged("__first_row");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string @__last_row {
            get {
                return this.@__last_rowField;
            }
            set {
                this.@__last_rowField = value;
                this.RaisePropertyChanged("__last_row");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/x_264731_choreszer_customers")]
    public partial class getKeysResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] sys_idField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sys_id", Order=0)]
        public string[] sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKeysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/x_264731_choreszer_customers", Order=0)]
        public Temp.Reference_NowPlatform.getKeys getKeys;
        
        public getKeysRequest() {
        }
        
        public getKeysRequest(Temp.Reference_NowPlatform.getKeys getKeys) {
            this.getKeys = getKeys;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKeysResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/x_264731_choreszer_customers", Order=0)]
        public Temp.Reference_NowPlatform.getKeysResponse getKeysResponse;
        
        public getKeysResponse1() {
        }
        
        public getKeysResponse1(Temp.Reference_NowPlatform.getKeysResponse getKeysResponse) {
            this.getKeysResponse = getKeysResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/x_264731_choreszer_customers")]
    public partial class deleteRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sys_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/x_264731_choreszer_customers")]
    public partial class deleteRecordResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/x_264731_choreszer_customers", Order=0)]
        public Temp.Reference_NowPlatform.deleteRecord deleteRecord;
        
        public deleteRecordRequest() {
        }
        
        public deleteRecordRequest(Temp.Reference_NowPlatform.deleteRecord deleteRecord) {
            this.deleteRecord = deleteRecord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteRecordResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/x_264731_choreszer_customers", Order=0)]
        public Temp.Reference_NowPlatform.deleteRecordResponse deleteRecordResponse;
        
        public deleteRecordResponse1() {
        }
        
        public deleteRecordResponse1(Temp.Reference_NowPlatform.deleteRecordResponse deleteRecordResponse) {
            this.deleteRecordResponse = deleteRecordResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/x_264731_choreszer_customers")]
    public partial class get : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sys_idField;
        
        private string @__use_viewField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string @__use_view {
            get {
                return this.@__use_viewField;
            }
            set {
                this.@__use_viewField = value;
                this.RaisePropertyChanged("__use_view");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/x_264731_choreszer_customers")]
    public partial class getResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string first_nameField;
        
        private string last_nameField;
        
        private string numberField;
        
        private string phone_numberField;
        
        private string sys_created_byField;
        
        private string sys_created_onField;
        
        private string sys_idField;
        
        private string sys_mod_countField;
        
        private string sys_updated_byField;
        
        private string sys_updated_onField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                this.first_nameField = value;
                this.RaisePropertyChanged("first_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
                this.RaisePropertyChanged("last_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string phone_number {
            get {
                return this.phone_numberField;
            }
            set {
                this.phone_numberField = value;
                this.RaisePropertyChanged("phone_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sys_created_by {
            get {
                return this.sys_created_byField;
            }
            set {
                this.sys_created_byField = value;
                this.RaisePropertyChanged("sys_created_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sys_created_on {
            get {
                return this.sys_created_onField;
            }
            set {
                this.sys_created_onField = value;
                this.RaisePropertyChanged("sys_created_on");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=7)]
        public string sys_mod_count {
            get {
                return this.sys_mod_countField;
            }
            set {
                this.sys_mod_countField = value;
                this.RaisePropertyChanged("sys_mod_count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string sys_updated_by {
            get {
                return this.sys_updated_byField;
            }
            set {
                this.sys_updated_byField = value;
                this.RaisePropertyChanged("sys_updated_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string sys_updated_on {
            get {
                return this.sys_updated_onField;
            }
            set {
                this.sys_updated_onField = value;
                this.RaisePropertyChanged("sys_updated_on");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/x_264731_choreszer_customers", Order=0)]
        public Temp.Reference_NowPlatform.get get;
        
        public getRequest() {
        }
        
        public getRequest(Temp.Reference_NowPlatform.get get) {
            this.get = get;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/x_264731_choreszer_customers", Order=0)]
        public Temp.Reference_NowPlatform.getResponse getResponse;
        
        public getResponse1() {
        }
        
        public getResponse1(Temp.Reference_NowPlatform.getResponse getResponse) {
            this.getResponse = getResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/x_264731_choreszer_customers")]
    public partial class getRecords : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string first_nameField;
        
        private string last_nameField;
        
        private string numberField;
        
        private string phone_numberField;
        
        private string sys_created_byField;
        
        private string sys_created_onField;
        
        private string sys_idField;
        
        private string sys_mod_countField;
        
        private string sys_updated_byField;
        
        private string sys_updated_onField;
        
        private string @__use_viewField;
        
        private string @__encoded_queryField;
        
        private string @__limitField;
        
        private string @__first_rowField;
        
        private string @__last_rowField;
        
        private string @__order_byField;
        
        private string @__order_by_descField;
        
        private string @__exclude_columnsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                this.first_nameField = value;
                this.RaisePropertyChanged("first_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
                this.RaisePropertyChanged("last_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string phone_number {
            get {
                return this.phone_numberField;
            }
            set {
                this.phone_numberField = value;
                this.RaisePropertyChanged("phone_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sys_created_by {
            get {
                return this.sys_created_byField;
            }
            set {
                this.sys_created_byField = value;
                this.RaisePropertyChanged("sys_created_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sys_created_on {
            get {
                return this.sys_created_onField;
            }
            set {
                this.sys_created_onField = value;
                this.RaisePropertyChanged("sys_created_on");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=7)]
        public string sys_mod_count {
            get {
                return this.sys_mod_countField;
            }
            set {
                this.sys_mod_countField = value;
                this.RaisePropertyChanged("sys_mod_count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string sys_updated_by {
            get {
                return this.sys_updated_byField;
            }
            set {
                this.sys_updated_byField = value;
                this.RaisePropertyChanged("sys_updated_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string sys_updated_on {
            get {
                return this.sys_updated_onField;
            }
            set {
                this.sys_updated_onField = value;
                this.RaisePropertyChanged("sys_updated_on");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string @__use_view {
            get {
                return this.@__use_viewField;
            }
            set {
                this.@__use_viewField = value;
                this.RaisePropertyChanged("__use_view");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string @__encoded_query {
            get {
                return this.@__encoded_queryField;
            }
            set {
                this.@__encoded_queryField = value;
                this.RaisePropertyChanged("__encoded_query");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string @__limit {
            get {
                return this.@__limitField;
            }
            set {
                this.@__limitField = value;
                this.RaisePropertyChanged("__limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string @__first_row {
            get {
                return this.@__first_rowField;
            }
            set {
                this.@__first_rowField = value;
                this.RaisePropertyChanged("__first_row");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string @__last_row {
            get {
                return this.@__last_rowField;
            }
            set {
                this.@__last_rowField = value;
                this.RaisePropertyChanged("__last_row");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string @__order_by {
            get {
                return this.@__order_byField;
            }
            set {
                this.@__order_byField = value;
                this.RaisePropertyChanged("__order_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string @__order_by_desc {
            get {
                return this.@__order_by_descField;
            }
            set {
                this.@__order_by_descField = value;
                this.RaisePropertyChanged("__order_by_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string @__exclude_columns {
            get {
                return this.@__exclude_columnsField;
            }
            set {
                this.@__exclude_columnsField = value;
                this.RaisePropertyChanged("__exclude_columns");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.service-now.com/x_264731_choreszer_customers")]
    public partial class getRecordsResponseGetRecordsResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string first_nameField;
        
        private string last_nameField;
        
        private string numberField;
        
        private string phone_numberField;
        
        private string sys_created_byField;
        
        private string sys_created_onField;
        
        private string sys_idField;
        
        private string sys_mod_countField;
        
        private string sys_updated_byField;
        
        private string sys_updated_onField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                this.first_nameField = value;
                this.RaisePropertyChanged("first_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
                this.RaisePropertyChanged("last_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string phone_number {
            get {
                return this.phone_numberField;
            }
            set {
                this.phone_numberField = value;
                this.RaisePropertyChanged("phone_number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sys_created_by {
            get {
                return this.sys_created_byField;
            }
            set {
                this.sys_created_byField = value;
                this.RaisePropertyChanged("sys_created_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sys_created_on {
            get {
                return this.sys_created_onField;
            }
            set {
                this.sys_created_onField = value;
                this.RaisePropertyChanged("sys_created_on");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sys_id {
            get {
                return this.sys_idField;
            }
            set {
                this.sys_idField = value;
                this.RaisePropertyChanged("sys_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=7)]
        public string sys_mod_count {
            get {
                return this.sys_mod_countField;
            }
            set {
                this.sys_mod_countField = value;
                this.RaisePropertyChanged("sys_mod_count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string sys_updated_by {
            get {
                return this.sys_updated_byField;
            }
            set {
                this.sys_updated_byField = value;
                this.RaisePropertyChanged("sys_updated_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string sys_updated_on {
            get {
                return this.sys_updated_onField;
            }
            set {
                this.sys_updated_onField = value;
                this.RaisePropertyChanged("sys_updated_on");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.service-now.com/x_264731_choreszer_customers", Order=0)]
        public Temp.Reference_NowPlatform.getRecords getRecords;
        
        public getRecordsRequest() {
        }
        
        public getRecordsRequest(Temp.Reference_NowPlatform.getRecords getRecords) {
            this.getRecords = getRecords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRecordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRecordsResponse", Namespace="http://www.service-now.com/x_264731_choreszer_customers", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getRecordsResult", IsNullable=false)]
        public Temp.Reference_NowPlatform.getRecordsResponseGetRecordsResult[] getRecordsResponse1;
        
        public getRecordsResponse() {
        }
        
        public getRecordsResponse(Temp.Reference_NowPlatform.getRecordsResponseGetRecordsResult[] getRecordsResponse1) {
            this.getRecordsResponse1 = getRecordsResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceNowSoapChannel : Temp.Reference_NowPlatform.ServiceNowSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceNowSoapClient : System.ServiceModel.ClientBase<Temp.Reference_NowPlatform.ServiceNowSoap>, Temp.Reference_NowPlatform.ServiceNowSoap {
        
        public ServiceNowSoapClient() {
        }
        
        public ServiceNowSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceNowSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNowSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNowSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Temp.Reference_NowPlatform.insertResponse1 Temp.Reference_NowPlatform.ServiceNowSoap.insert(Temp.Reference_NowPlatform.insertRequest request) {
            return base.Channel.insert(request);
        }
        
        public Temp.Reference_NowPlatform.insertResponse insert(Temp.Reference_NowPlatform.insert insert1) {
            Temp.Reference_NowPlatform.insertRequest inValue = new Temp.Reference_NowPlatform.insertRequest();
            inValue.insert = insert1;
            Temp.Reference_NowPlatform.insertResponse1 retVal = ((Temp.Reference_NowPlatform.ServiceNowSoap)(this)).insert(inValue);
            return retVal.insertResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Temp.Reference_NowPlatform.insertResponse1> Temp.Reference_NowPlatform.ServiceNowSoap.insertAsync(Temp.Reference_NowPlatform.insertRequest request) {
            return base.Channel.insertAsync(request);
        }
        
        public System.Threading.Tasks.Task<Temp.Reference_NowPlatform.insertResponse1> insertAsync(Temp.Reference_NowPlatform.insert insert) {
            Temp.Reference_NowPlatform.insertRequest inValue = new Temp.Reference_NowPlatform.insertRequest();
            inValue.insert = insert;
            return ((Temp.Reference_NowPlatform.ServiceNowSoap)(this)).insertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Temp.Reference_NowPlatform.updateResponse1 Temp.Reference_NowPlatform.ServiceNowSoap.update(Temp.Reference_NowPlatform.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public Temp.Reference_NowPlatform.updateResponse update(Temp.Reference_NowPlatform.update update1) {
            Temp.Reference_NowPlatform.updateRequest inValue = new Temp.Reference_NowPlatform.updateRequest();
            inValue.update = update1;
            Temp.Reference_NowPlatform.updateResponse1 retVal = ((Temp.Reference_NowPlatform.ServiceNowSoap)(this)).update(inValue);
            return retVal.updateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Temp.Reference_NowPlatform.updateResponse1> Temp.Reference_NowPlatform.ServiceNowSoap.updateAsync(Temp.Reference_NowPlatform.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Temp.Reference_NowPlatform.updateResponse1> updateAsync(Temp.Reference_NowPlatform.update update) {
            Temp.Reference_NowPlatform.updateRequest inValue = new Temp.Reference_NowPlatform.updateRequest();
            inValue.update = update;
            return ((Temp.Reference_NowPlatform.ServiceNowSoap)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Temp.Reference_NowPlatform.deleteMultipleResponse1 Temp.Reference_NowPlatform.ServiceNowSoap.deleteMultiple(Temp.Reference_NowPlatform.deleteMultipleRequest request) {
            return base.Channel.deleteMultiple(request);
        }
        
        public Temp.Reference_NowPlatform.deleteMultipleResponse deleteMultiple(Temp.Reference_NowPlatform.deleteMultiple deleteMultiple1) {
            Temp.Reference_NowPlatform.deleteMultipleRequest inValue = new Temp.Reference_NowPlatform.deleteMultipleRequest();
            inValue.deleteMultiple = deleteMultiple1;
            Temp.Reference_NowPlatform.deleteMultipleResponse1 retVal = ((Temp.Reference_NowPlatform.ServiceNowSoap)(this)).deleteMultiple(inValue);
            return retVal.deleteMultipleResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Temp.Reference_NowPlatform.deleteMultipleResponse1> Temp.Reference_NowPlatform.ServiceNowSoap.deleteMultipleAsync(Temp.Reference_NowPlatform.deleteMultipleRequest request) {
            return base.Channel.deleteMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Temp.Reference_NowPlatform.deleteMultipleResponse1> deleteMultipleAsync(Temp.Reference_NowPlatform.deleteMultiple deleteMultiple) {
            Temp.Reference_NowPlatform.deleteMultipleRequest inValue = new Temp.Reference_NowPlatform.deleteMultipleRequest();
            inValue.deleteMultiple = deleteMultiple;
            return ((Temp.Reference_NowPlatform.ServiceNowSoap)(this)).deleteMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Temp.Reference_NowPlatform.getKeysResponse1 Temp.Reference_NowPlatform.ServiceNowSoap.getKeys(Temp.Reference_NowPlatform.getKeysRequest request) {
            return base.Channel.getKeys(request);
        }
        
        public Temp.Reference_NowPlatform.getKeysResponse getKeys(Temp.Reference_NowPlatform.getKeys getKeys1) {
            Temp.Reference_NowPlatform.getKeysRequest inValue = new Temp.Reference_NowPlatform.getKeysRequest();
            inValue.getKeys = getKeys1;
            Temp.Reference_NowPlatform.getKeysResponse1 retVal = ((Temp.Reference_NowPlatform.ServiceNowSoap)(this)).getKeys(inValue);
            return retVal.getKeysResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Temp.Reference_NowPlatform.getKeysResponse1> Temp.Reference_NowPlatform.ServiceNowSoap.getKeysAsync(Temp.Reference_NowPlatform.getKeysRequest request) {
            return base.Channel.getKeysAsync(request);
        }
        
        public System.Threading.Tasks.Task<Temp.Reference_NowPlatform.getKeysResponse1> getKeysAsync(Temp.Reference_NowPlatform.getKeys getKeys) {
            Temp.Reference_NowPlatform.getKeysRequest inValue = new Temp.Reference_NowPlatform.getKeysRequest();
            inValue.getKeys = getKeys;
            return ((Temp.Reference_NowPlatform.ServiceNowSoap)(this)).getKeysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Temp.Reference_NowPlatform.deleteRecordResponse1 Temp.Reference_NowPlatform.ServiceNowSoap.deleteRecord(Temp.Reference_NowPlatform.deleteRecordRequest request) {
            return base.Channel.deleteRecord(request);
        }
        
        public Temp.Reference_NowPlatform.deleteRecordResponse deleteRecord(Temp.Reference_NowPlatform.deleteRecord deleteRecord1) {
            Temp.Reference_NowPlatform.deleteRecordRequest inValue = new Temp.Reference_NowPlatform.deleteRecordRequest();
            inValue.deleteRecord = deleteRecord1;
            Temp.Reference_NowPlatform.deleteRecordResponse1 retVal = ((Temp.Reference_NowPlatform.ServiceNowSoap)(this)).deleteRecord(inValue);
            return retVal.deleteRecordResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Temp.Reference_NowPlatform.deleteRecordResponse1> Temp.Reference_NowPlatform.ServiceNowSoap.deleteRecordAsync(Temp.Reference_NowPlatform.deleteRecordRequest request) {
            return base.Channel.deleteRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Temp.Reference_NowPlatform.deleteRecordResponse1> deleteRecordAsync(Temp.Reference_NowPlatform.deleteRecord deleteRecord) {
            Temp.Reference_NowPlatform.deleteRecordRequest inValue = new Temp.Reference_NowPlatform.deleteRecordRequest();
            inValue.deleteRecord = deleteRecord;
            return ((Temp.Reference_NowPlatform.ServiceNowSoap)(this)).deleteRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Temp.Reference_NowPlatform.getResponse1 Temp.Reference_NowPlatform.ServiceNowSoap.get(Temp.Reference_NowPlatform.getRequest request) {
            return base.Channel.get(request);
        }
        
        public Temp.Reference_NowPlatform.getResponse get(Temp.Reference_NowPlatform.get get1) {
            Temp.Reference_NowPlatform.getRequest inValue = new Temp.Reference_NowPlatform.getRequest();
            inValue.get = get1;
            Temp.Reference_NowPlatform.getResponse1 retVal = ((Temp.Reference_NowPlatform.ServiceNowSoap)(this)).get(inValue);
            return retVal.getResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Temp.Reference_NowPlatform.getResponse1> Temp.Reference_NowPlatform.ServiceNowSoap.getAsync(Temp.Reference_NowPlatform.getRequest request) {
            return base.Channel.getAsync(request);
        }
        
        public System.Threading.Tasks.Task<Temp.Reference_NowPlatform.getResponse1> getAsync(Temp.Reference_NowPlatform.get get) {
            Temp.Reference_NowPlatform.getRequest inValue = new Temp.Reference_NowPlatform.getRequest();
            inValue.get = get;
            return ((Temp.Reference_NowPlatform.ServiceNowSoap)(this)).getAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Temp.Reference_NowPlatform.getRecordsResponse Temp.Reference_NowPlatform.ServiceNowSoap.getRecords(Temp.Reference_NowPlatform.getRecordsRequest request) {
            return base.Channel.getRecords(request);
        }
        
        public Temp.Reference_NowPlatform.getRecordsResponseGetRecordsResult[] getRecords(Temp.Reference_NowPlatform.getRecords getRecords1) {
            Temp.Reference_NowPlatform.getRecordsRequest inValue = new Temp.Reference_NowPlatform.getRecordsRequest();
            inValue.getRecords = getRecords1;
            Temp.Reference_NowPlatform.getRecordsResponse retVal = ((Temp.Reference_NowPlatform.ServiceNowSoap)(this)).getRecords(inValue);
            return retVal.getRecordsResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Temp.Reference_NowPlatform.getRecordsResponse> Temp.Reference_NowPlatform.ServiceNowSoap.getRecordsAsync(Temp.Reference_NowPlatform.getRecordsRequest request) {
            return base.Channel.getRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Temp.Reference_NowPlatform.getRecordsResponse> getRecordsAsync(Temp.Reference_NowPlatform.getRecords getRecords) {
            Temp.Reference_NowPlatform.getRecordsRequest inValue = new Temp.Reference_NowPlatform.getRecordsRequest();
            inValue.getRecords = getRecords;
            return ((Temp.Reference_NowPlatform.ServiceNowSoap)(this)).getRecordsAsync(inValue);
        }
    }
}
