version: '3.4'

services:
  webapplication1:
    image: webapplication1:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webapplication1$
    volumes:
      - C:\Users\azam5\Source\Repos\WebApplication1\WebApplication1:/app
      - C:\Users\azam5\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_webapplication1$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webapplication1$ bin/Debug/netcoreapp2.1/WebApplication1.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
